type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

scalar Date

input PaginationInput {
  page: Int = 1
  perPage: Int = 20
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  totalCount: Int!
  page: Int!
  perPage: Int!
}
